const modules = [
    {
        name: 'project_common__hero',
        group: 'component',
        type: 'project',
        title: 'Project: Hero banner',
        thumbnail: '/img/thumbnails/projects/common/hero.jpg',
        context: require('./common/hero'),
    },
    {
        name: 'project_common__next_project',
        group: 'component',
        type: 'project',
        title: 'Project: Next Project block',
        thumbnail: '/img/thumbnails/projects/common/next_project.jpg',
        context: require('./common/next_project'),
    },
    {
        name: 'project_common__about',
        group: 'component',
        type: 'project',
        title: 'Project: About block',
        thumbnail: '/img/thumbnails/projects/common/about.jpg',
        context: require('./common/about'),
    },
    {
        name: 'project_common__overview',
        group: 'component',
        type: 'project',
        title: 'Project: Overview Block',
        thumbnail: '/img/thumbnails/projects/common/overview.jpg',
        context: require('./common/overview'),
    },
    {
        name: 'project_common__images',
        group: 'component',
        type: 'project',
        title: 'Project: Images Block',
        thumbnail: '/img/thumbnails/projects/common/images.jpg',
        context: require('./common/images'),
    },
    {
        name: 'project_common__screenshot',
        group: 'component',
        type: 'project',
        title: 'Project: Screenshot',
        thumbnail: '/img/thumbnails/projects/common/screenshot.jpg',
        context: require('./common/screenshot'),
    },
    {
        name: 'project_common__screenshot_big',
        group: 'component',
        type: 'project',
        title: 'Project: Screenshot Big',
        thumbnail: '/img/thumbnails/projects/common/screenshot_big.jpg',
        context: require('./common/screenshot_big'),
    },
    {
        name: 'project_common__review',
        group: 'component',
        type: 'project',
        title: 'Project: Review',
        thumbnail: '/img/thumbnails/projects/common/review.jpg',
        context: require('./common/review'),
    },
    {
        name: 'project_common__partnership',
        group: 'component',
        type: 'project',
        title: 'Project: Partnership',
        thumbnail: '/img/thumbnails/projects/common/partnership.jpg',
        context: require('./common/partnership'),
    },
    {
        name: 'project_common__numbers',
        group: 'component',
        type: 'project',
        title: 'Project: Numbers',
        thumbnail: '/img/thumbnails/projects/common/numbers.jpg',
        context: require('./common/numbers'),
    },
    {
        name: 'project_common__totals',
        group: 'component',
        type: 'project',
        title: 'Project: Totals',
        thumbnail: '/img/thumbnails/projects/common/totals.jpg',
        context: require('./common/totals'),
    },
    {
        name: 'project_common__stats',
        group: 'component',
        type: 'project',
        title: 'Project: Stats',
        thumbnail: '/img/thumbnails/projects/common/stats.jpg',
        context: require('./common/stats'),
    },
    {
        name: 'project_common__results',
        group: 'component',
        type: 'project',
        title: 'Project: Results',
        thumbnail: '/img/thumbnails/projects/common/results.jpg',
        context: require('./common/results'),
    },
    {
        name: 'project_common__screens',
        group: 'component',
        type: 'project',
        title: 'Project: Screens',
        thumbnail: '/img/thumbnails/projects/common/screens.jpg',
        context: require('./common/screens'),
    },
    {
        name: 'project_common__numbers_text',
        group: 'component',
        type: 'project',
        title: 'Project: Numbers w/ Text only',
        thumbnail: '/img/thumbnails/projects/common/numbers_text.png',
        context: require('./common/numberWithText'),
    },
    {
        name: 'project_common__numbers_image',
        group: 'component',
        type: 'project',
        title: 'Project: Numbers w/ Image only',
        thumbnail: '/img/thumbnails/projects/common/block_with_image.jpg',
        context: require('./common/numberWithImage'),
    },
    {
        name: 'project_common__devices_screenshots',
        group: 'component',
        type: 'project',
        title: 'Project: Devices Screenshots',
        thumbnail: '/img/thumbnails/projects/common/devices_screenshots.png',
        context: require('./common/devicesScreenshots'),
    },
    {
        name: 'fsu_project__ui',
        group: 'text',
        type: 'project',
        title: 'FSU: UI',
        thumbnail: '/img/thumbnails/projects/fsu/ui.jpg',
        context: require('./fsu/ui'),
    },
];

export default modules;
